// types.js

// Authentication
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// User
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';


// Course

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';


// Modules
export const FETCH_MODULES_REQUEST = 'FETCH_MODULES_REQUEST';
export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS';
export const FETCH_MODULES_FAILURE = 'FETCH_MODULES_FAILURE';

// Enrollments
export const FETCH_ENROLLMENTS_REQUEST = 'FETCH_ENROLLMENTS_REQUEST';
export const FETCH_ENROLLMENTS_SUCCESS = 'FETCH_ENROLLMENTS_SUCCESS';
export const FETCH_ENROLLMENTS_FAILURE = 'FETCH_ENROLLMENTS_FAILURE';

export const ENROLL_COURSES_REQUEST = 'ENROLL_COURSES_REQUEST';
export const ENROLL_COURSES_SUCCESS = 'ENROLL_COURSES_SUCCESS';
export const ENROLL_COURSES_FAILURE = 'ENROLL_COURSES_FAILURE';

export const UNENROLL_COURSES_REQUEST = 'UNENROLL_COURSES_REQUEST';
export const UNENROLL_COURSES_SUCCESS = 'UNENROLL_COURSES_SUCCESS';
export const UNENROLL_COURSES_FAILURE = 'UNENROLL_COURSES_FAILURE';

export const UPDATE_PROGRESS_REQUEST = 'UPDATE_PROGRESS_REQUEST';
export const UPDATE_PROGRESS_SUCCESS = 'UPDATE_PROGRESS_SUCCESS';
export const UPDATE_PROGRESS_FAILURE = 'UPDATE_PROGRESS_FAILURE';

// Quizzes
export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';

export const SUBMIT_QUIZ_REQUEST = 'SUBMIT_QUIZ_REQUEST';
export const SUBMIT_QUIZ_SUCCESS = 'SUBMIT_QUIZ_SUCCESS';
export const SUBMIT_QUIZ_FAILURE = 'SUBMIT_QUIZ_FAILURE';

// Resources
export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE';

export const UPLOAD_RESOURCE_REQUEST = 'UPLOAD_RESOURCE_REQUEST';
export const UPLOAD_RESOURCE_SUCCESS = 'UPLOAD_RESOURCE_SUCCESS';
export const UPLOAD_RESOURCE_FAILURE = 'UPLOAD_RESOURCE_FAILURE';

// Forum
export const FETCH_FORUM_POSTS_REQUEST = 'FETCH_FORUM_POSTS_REQUEST';
export const FETCH_FORUM_POSTS_SUCCESS = 'FETCH_FORUM_POSTS_SUCCESS';
export const FETCH_FORUM_POSTS_FAILURE = 'FETCH_FORUM_POSTS_FAILURE';

export const CREATE_FORUM_POST_REQUEST = 'CREATE_FORUM_POST_REQUEST';
export const CREATE_FORUM_POST_SUCCESS = 'CREATE_FORUM_POST_SUCCESS';
export const CREATE_FORUM_POST_FAILURE = 'CREATE_FORUM_POST_FAILURE';

// Adaptive Learning
export const FETCH_RECOMMENDATIONS_REQUEST = 'FETCH_RECOMMENDATIONS_REQUEST';
export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS';
export const FETCH_RECOMMENDATIONS_FAILURE = 'FETCH_RECOMMENDATIONS_FAILURE';

// Comments
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

// Chat
export const JOIN_CHAT_ROOM_REQUEST = 'JOIN_CHAT_ROOM_REQUEST';
export const JOIN_CHAT_ROOM_SUCCESS = 'JOIN_CHAT_ROOM_SUCCESS';
export const JOIN_CHAT_ROOM_FAILURE = 'JOIN_CHAT_ROOM_FAILURE';

export const LEAVE_CHAT_ROOM_REQUEST = 'LEAVE_CHAT_ROOM_REQUEST';
export const LEAVE_CHAT_ROOM_SUCCESS = 'LEAVE_CHAT_ROOM_SUCCESS';
export const LEAVE_CHAT_ROOM_FAILURE = 'LEAVE_CHAT_ROOM_FAILURE';

export const SEND_CHAT_MESSAGE_REQUEST = 'SEND_CHAT_MESSAGE_REQUEST';
export const SEND_CHAT_MESSAGE_SUCCESS = 'SEND_CHAT_MESSAGE_SUCCESS';
export const SEND_CHAT_MESSAGE_FAILURE = 'SEND_CHAT_MESSAGE_FAILURE';

export const RECEIVE_CHAT_MESSAGE = 'RECEIVE_CHAT_MESSAGE';
export const SET_TYPING_INDICATOR = 'SET_TYPING_INDICATOR';

export const FETCH_CHAT_MESSAGES_REQUEST = 'FETCH_CHAT_MESSAGES_REQUEST';
export const FETCH_CHAT_MESSAGES_SUCCESS = 'FETCH_CHAT_MESSAGES_SUCCESS';
export const FETCH_CHAT_MESSAGES_FAILURE = 'FETCH_CHAT_MESSAGES_FAILURE';

export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';

// Review
export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';  
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';  
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE'; 

