# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Microsoft Security DevOps (MSDO) is a command line application which integrates static analysis tools into the development cycle.
# MSDO installs, configures and runs the latest versions of static analysis tools
# (including, but not limited to, SDL/security and compliance tools).
#
# The Microsoft Security DevOps action is currently in beta and runs on the windows-latest queue,
# as well as Windows self hosted agents. ubuntu-latest support coming soon.
#
# For more information about the action , check out https://github.com/microsoft/security-devops-action
#
# Please note this workflow do not integrate your GitHub Org with Microsoft Defender For DevOps. You have to create an integration
# and provide permission before this can report data back to azure.
# Read the official documentation here : https://learn.microsoft.com/en-us/azure/defender-for-cloud/quickstart-onboard-github

name: Microsoft Defender For Devops

on: [push]

jobs:
  MSDO:
    runs-on: windows-latest
    permissions:
      contents: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize MSDO
      uses: microsoft/security-devops-action/init@beta
      with:
        # Specify configuration options here
        # Ensure the path to the config file is correct

    - name: Run MSDO Analysis
      uses: microsoft/security-devops-action/analyze@beta
      with:
        # Specify analysis options here
