name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      # Run migrations
      - name: Apply migrations
        run: python manage.py migrate

      # Run tests
      - name: Run tests
        run: python manage.py test

      # Run linters
      - name: Run linters
        run: |
          pip install flake8
          flake8 .
      
      - name: Static analysis
        run: |
          pip install pylint
          pylint backend
      
      # Run security checks
      - name: Run security checks
        run: |
          pip install bandit
          bandit -r .
      
      # Run dependency checks
      - name: Run dependency checks
        run: |
          pip install safety
          safety check
      
      # Run code coverage
      - name: Run code coverage
        run: |
          pip install coverage
          coverage run --source='.' manage.py test
          coverage report
          coverage xml
          pip install codecov
          codecov
      