name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      # Run migrations
      - name: Apply migrations
        run: python manage.py migrate

      # Run tests
      - name: Run tests
        run: python manage.py test

      # Optional: Add steps for linting, static analysis, or other CI tasks