name: Build Conda Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-file: environment.yml  # Path to your environment.yml
        activate-environment: my_django_project

    - name: Build Conda
      uses: cascode-labs/build-conda-action@v0.1.4
      with:
        recipe_path: conda-recipe  # Update this if your recipe is in a different directory
        conda_build_env_filepath: environment.yml  # Path to your environment.yml file
        conda_build_env_name: my_django_project  # Name of your conda environment
        base_env_prefix: /usr/share/miniconda
        package_artifact_name: conda_package
        test_results_artifact_name: test_results
        build_options: "-c defaults -c conda-forge"
